export const CALL_SUMMARY = "CALL_SUMMARY";
export const GATEWAY_SUMMARY = "GATEWAY_SUMMARY";
export const AGENT_SUMMARY = "AGENT_SUMMARY";
export const AGENT_KPI = "AGENT_KPI";
export const ORDER_SUMMARY = "ORDER_SUMMARY";
export const CALL_FEEDBACK_SUMMARY = "CALL_FEEDBACK_SUMMARY";
export const CALL_MONTHLY_SUMMARY = "CALL_MONTHLY_SUMMARY";
export const FEEDBACK_SUMMARY = "FEEDBACK_SUMMARY";

export default {
    CALL_SUMMARY,
    GATEWAY_SUMMARY,
    AGENT_SUMMARY,
    AGENT_KPI,
    ORDER_SUMMARY,
    FEEDBACK_SUMMARY,
    CALL_MONTHLY_SUMMARY,
    CALL_FEEDBACK_SUMMARY
};
