export const EXTENSION_LIST = "EXTENSION_LIST";
export const EXTENSION_ADD = "EXTENSION_ADD";
export const EXTENSION_UPDATE = "EXTENSION_UPDATE";
export const EXTENSION_REMOVE = "EXTENSION_REMOVE";

export const GATEWAY_LIST = "GATEWAY_LIST";
export const GATEWAY_ADD = "GATEWAY_ADD";
export const GATEWAY_UPDATE = "GATEWAY_UPDATE";
export const GATEWAY_REMOVE = "GATEWAY_REMOVE";


export const CAMPAIGN_LIST = "CAMPAIGN_LIST";
export const CAMPAIGN_ADD = "CAMPAIGN_ADD";
export const CAMPAIGN_UPDATE = "CAMPAIGN_UPDATE";
export const CAMPAIGN_REMOVE = "CAMPAIGN_REMOVE";

export const CAMPAIGN_LIST_LIST = "CAMPAIGN_LIST_LIST";
export const CAMPAIGN_LIST_ADD = "CAMPAIGN_LIST_ADD";
export const CAMPAIGN_LIST_UPDATE = "CAMPAIGN_LIST_UPDATE";
export const CAMPAIGN_LIST_REMOVE = "CAMPAIGN_LIST_REMOVE";

export const CAMPAIGN_LIST_RECIPIENT_ADD = "CAMPAIGN_LIST_RECIPIENT_ADD";
export const CAMPAIGN_LIST_RECIPIENT_REMOVE = "CAMPAIGN_LIST_RECIPIENT_REMOVE";

export const FEEDBACK_LIST = "FEEDBACK_LIST";
export const FEEDBACK_ADD = "FEEDBACK_ADD";
export const FEEDBACK_UPDATE = "FEEDBACK_UPDATE";
export const FEEDBACK_REMOVE = "FEEDBACK_REMOVE";

export const CALLBACK_LIST = "CALLBACK_LIST";
export const CALLBACK_ADD = "CALLBACK_ADD";
export const CALLBACK_UPDATE = "CALLBACK_UPDATE";
export const CALLBACK_REMOVE = "CALLBACK_REMOVE";

export const CALL_LOG_LIST = "CALL_LOG_LIST";
export const CALL_LOG_ADD = "CALL_LOG_ADD";
export const CALL_LOG_UPDATE = "CALL_LOG_UPDATE";

export const ORDER_ITEM_LIST = "ORDER_ITEM_LIST";
export const ORDER_ITEM_ADD = "ORDER_ITEM_ADD";
export const ORDER_ITEM_UPDATE = "ORDER_ITEM_UPDATE";
export const ORDER_ITEM_REMOVE = "ORDER_ITEM_REMOVE";

export const SOCKET_INIT = "SOCKET_INIT";

export const CALL_EVENT_LIST = "CALL_EVENT_LIST";
export const CALL_EVENT_ADD = "CALL_EVENT_ADD";
export const CALL_UPDATE = "CALL_UPDATE";
export const CALL_ADD = "CALL_ADD";

export const MY_CALL_LIST = "MY_CALL_LIST";
export const MY_CALL_UPDATE = "MY_CALL_UPDATE";
export const MY_CALL_REMOVE = "MY_CALL_REMOVE";
export const MY_CALL_ADD = "MY_CALL_ADD";

export default {
    EXTENSION_LIST,
    EXTENSION_ADD,
    EXTENSION_UPDATE,
    EXTENSION_REMOVE,
    GATEWAY_LIST,
    GATEWAY_ADD,
    GATEWAY_UPDATE,
    GATEWAY_REMOVE,
    CAMPAIGN_LIST,
    CAMPAIGN_ADD,
    CAMPAIGN_UPDATE,
    CAMPAIGN_REMOVE,
    CAMPAIGN_LIST_LIST,
    CAMPAIGN_LIST_ADD,
    CAMPAIGN_LIST_UPDATE,
    CAMPAIGN_LIST_REMOVE,
    CAMPAIGN_LIST_RECIPIENT_ADD,
    CAMPAIGN_LIST_RECIPIENT_REMOVE,
    FEEDBACK_LIST,
    FEEDBACK_ADD,
    FEEDBACK_UPDATE,
    FEEDBACK_REMOVE,
    CALLBACK_ADD,
    CALLBACK_UPDATE,
    CALLBACK_REMOVE,
    CALLBACK_LIST,
    CALL_LOG_LIST,
    CALL_LOG_ADD,
    CALL_LOG_UPDATE,
    SOCKET_INIT,
    CALL_EVENT_LIST,
    CALL_EVENT_ADD,
    CALL_UPDATE,
    CALL_ADD,
    MY_CALL_ADD,
    MY_CALL_LIST,
    MY_CALL_UPDATE,
    MY_CALL_REMOVE
};
