export const AGENT_FAQ_LIST = "AGENT_FAQ_LIST";
export const AGENT_FAQ_ADD = "AGENT_FAQ_ADD";
export const AGENT_FAQ_UPDATE = "AGENT_FAQ_UPDATE";
export const AGENT_FAQ_REMOVE = "AGENT_FAQ_REMOVE";

export const AGENT_FAQ_TOPIC_LIST = "AGENT_FAQ_TOPIC_LIST";
export const AGENT_FAQ_TOPIC_ADD = "AGENT_FAQ_TOPIC_ADD";
export const AGENT_FAQ_TOPIC_UPDATE = "AGENT_FAQ_TOPIC_UPDATE";
export const AGENT_FAQ_TOPIC_REMOVE = "AGENT_FAQ_TOPIC_REMOVE";

export default {
    AGENT_FAQ_LIST,
    AGENT_FAQ_ADD,
    AGENT_FAQ_UPDATE,
    AGENT_FAQ_REMOVE,
    AGENT_FAQ_TOPIC_LIST,
    AGENT_FAQ_TOPIC_ADD,
    AGENT_FAQ_TOPIC_UPDATE,
    AGENT_FAQ_TOPIC_REMOVE,
};
