export const COMPANY_LIST = "COMPANY_LIST";
export const COMPANY_ADD = "COMPANY_ADD";
export const COMPANY_UPDATE = "COMPANY_UPDATE";
export const COMPANY_REMOVE = "COMPANY_REMOVE";

export const CONTACT_LIST = "CONTACT_LIST";
export const CONTACT_ADD = "CONTACT_ADD";
export const CONTACT_UPDATE = "CONTACT_UPDATE";
export const CONTACT_REMOVE = "CONTACT_REMOVE";

export const LEAD_LIST = "LEAD_LIST";
export const LEAD_ADD = "LEAD_ADD";
export const LEAD_UPDATE = "LEAD_UPDATE";
export const LEAD_REMOVE = "LEAD_REMOVE";

export const ORDER_LIST = "ORDER_LIST";
export const ORDER_ADD = "ORDER_ADD";
export const ORDER_UPDATE = "ORDER_UPDATE";
export const ORDER_REMOVE = "ORDER_REMOVE";

export const ORDER_ITEM_LIST = "ORDER_ITEM_LIST";
export const ORDER_ITEM_ADD = "ORDER_ITEM_ADD";
export const ORDER_ITEM_UPDATE = "ORDER_ITEM_UPDATE";
export const ORDER_ITEM_REMOVE = "ORDER_ITEM_REMOVE";

export default {
    COMPANY_LIST,
    COMPANY_ADD,
    COMPANY_UPDATE,
    COMPANY_REMOVE,
    CONTACT_LIST,
    CONTACT_ADD,
    CONTACT_UPDATE,
    CONTACT_REMOVE,
    LEAD_LIST,
    LEAD_ADD,
    LEAD_UPDATE,
    LEAD_REMOVE,
    ORDER_LIST,
    ORDER_ADD,
    ORDER_UPDATE,
    ORDER_REMOVE,
    ORDER_ITEM_LIST,
    ORDER_ITEM_ADD,
    ORDER_ITEM_UPDATE,
    ORDER_ITEM_REMOVE
};
